# Generated by Django 3.2.5 on 2021-07-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='area_expr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
